name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Execute Jar File
        run: sudo kill -9 'sudo lsof -t -i:80' & sudo java -jar /home/ec2-user/actions-runner/_work/ventas/ventas/target/ventas.jar &
